### ISSUE TITLE
es6-promise not in package.json 

### ISSUE THREAD

**Issue by fredericlb** [AlexJozwicki/airflux#1]
Hi,

thanks for your work on this library !

I had some issues when adding it to my project since it requires es6-promise which is not in the package.json file.

Adding it did not work since it itself require a package named vertx that is not in the npm registry. To solve this I removed the dependency from Airflux and relied on Webpack implementation in my project. However, I'm aware that it won't work if the end user do not use a transpiler since Promise is not implemented in every browser. 

Since this is an ES6-aware library, maybe the dependency to es6-promise could be removed as Promise is part of es6 and the end user should use a polyfill.

**Comment by AlexJozwicki** [comment]
Hi,
Thank.
I'm currently in the process of ironing out the latest changes, including quite a lot in how actions are created. I'll try to document this in the next two days.

As for es6-promise, I'm still pondering whether or not this should be in this library.
I added it as a test to support IE10.
Basically, I now convinced that any and all polyfill should be in a file specific to your project, loaded before anything else, and that libraries like this one should not have any reference to polyfills.
Therefore you should have a polyfill.js in your project, with everything you need for your project/target browsers.
I'll keep you updated today.

**Comment by AlexJozwicki** [comment]
That said, it will give you the ability of chosing your own Promise polyfill.
But we're using currently es6-promise on our project without any issues of dependency not found.

**Comment by fredericlb** [comment]
Just updated and it works great with the new version.

Thanks for your help
