### ISSUE TITLE
React + Airflux full example

### ISSUE THREAD

**Issue by darkfrontcode** [AlexJozwicki/airflux#2]
Hi my friend, i'm working on React + Airflux, but i cant make they work together, the state always come undefined, but if i use airflux only with js it works like a charm.

Do you have any examples of react + airflux working together? 
In documentation of airflux dosent have a full exemple, only fragments of ramdom codes.

It would be helpful, thank you!

**Comment by AlexJozwicki** [comment]
Have you checked https://github.com/AlexJozwicki/reactmovie ?
Small tutorial for React I made, where airflux is introduced at some point (step 3 or 4).
Have a look at let me know if you're missing something.

I think the issue your referring is one I'm trying to "fix" right now:
When you use the FluxComponent as a superclass, it needs to set the state with the value of the store.
Hence, after the call to super is made, the state property is already set, meaning if you want to add properties to the state, you should not replace this.state but add properties to it.

From https://github.com/AlexJozwicki/reactmovie/blob/step-6/src/js/home.jsx

```
class Home extends FluxComponent {
    constructor( props ) {
        // we listen to the `movieAdded` action, which will call the `movieAdded` method of our class
        super( props, {
            movieAdded      : MovieActions.addMovie.action.completed,
            addMovieFailed  : MovieActions.addMovie.action.failed
        } );

        this.state = { notifications: Immutable.List()};
    }
```

**Comment by darkfrontcode** [comment]
Thank you, very, very mutch!

**Comment by AlexJozwicki** [comment]
I have a few ideas on how to manage to have the same syntax regardless of whether you have a Component or FluxComponent, but it is not that straightforward.
I will start bringing more ES6/7 features into airlfux soon, such as decorators that could maybe help.

**Comment by darkfrontcode** [comment]
I really, really, like your work. Keep this line, you do great thanks. ES6/7 decorators would be very nice way to do that, i read a few articles about this and looks a nice way to do that.

For me, i found this: https://github.com/ioweb-fr/generator-react-airflux, and i get those examples and react-movie that you pass to me, now, every thing is working. 

I really, apreciate you help and i will pass Airflux to my entire time .

Thank you, very mutch!
