### ISSUE TITLE
AirFlux with React-dom from react-router

### ISSUE THREAD

**Issue by darkfrontcode** [AlexJozwicki/airflux#3]
Hy, i am trying to use Airflux with the new version of react-router that uses react-dom from this link: https://www.npmjs.com/package/react-dom, but when i try use this two together, i get this error in my console:

npm ERR! peerinvalid Peer airflux@0.2.2 wants react@0.13.x
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2

Looks like the Airflux needs react 0.13 for dependencie, and react-dom needs react 0.14.

Can u help me on this? Thank You!

**Comment by AlexJozwicki** [comment]
Hi,
Sorry for the delay.
I'm planning on working on it in the next few days.
I'll try to at least deploy a quick fix today

**Comment by darkfrontcode** [comment]
Thank you for your answer!

I prefer a thousand times airflux than reduxx or reflux, haha.

Keep the great work, you have helped many people with it.

And I hope it gives you some money.

Thank you so mutch

Em terça-feira, 1 de dezembro de 2015, Alexandre Jozwicki <
notifications@github.com> escreveu:

**Comment by AlexJozwicki** [comment]
Hi,
I have an 0.3.0-alpha2 right now deployed which you can start testing.
Reasons is alpha2 is that I need to upgrade karma/mocha to work properly with the new version of babel and node, since the version I used break with the current node.
Once that is done, I will continue with ES6/ES7 features, run Flow on the whole project.

**Comment by darkfrontcode** [comment]
Got it.

Thank you for your feedback. In my next project I will start with this
alpha. If I have any issues, i will report them to you.

Thank you again and have a nice day.

Em quarta-feira, 2 de dezembro de 2015, Alexandre Jozwicki <
notifications@github.com> escreveu:

**Comment by darkfrontcode** [comment]
Hello Alex,

I just wanna say thank you for upgrade the newest version of the airflux,
it helped me a lot and now it is running with last version of react-router.

Keep the great work.

Have a nice day.

Em quarta-feira, 2 de dezembro de 2015, Wesley Custom udsndesign@gmail.com
escreveu:
