### ISSUE TITLE
Require Airflux is undefined

### ISSUE THREAD

**Issue by darkfrontcode** [AlexJozwicki/airflux#6]
hello my friend, after your last update, when I import Airflux, he is always undefined.

ex: import Airflux from 'airflux';

then when i call this module they always comesback undefined.
ex: console.log(Airflux) // undefined

but, if i call like this:

ex: import { Actions } from 'airflux'
console.log(Actions) // function actions

Error is always when i call airflux.

Can u fix this?

Thank you!

**Comment by AlexJozwicki** [comment]
You should use import \* as airflux from 'airflux'

**Comment by darkfrontcode** [comment]
Thank you, I will try this.
Have a nice day.

Em terça-feira, 16 de fevereiro de 2016, Alexandre Jozwicki <
notifications@github.com> escreveu:
